In [1]:
sentences= ['원숭이 엉덩이는 빨개',
'빨가면 사과 사과는 맛있어', 
'맛있으면 바나나 바나나는 길어', 
'길으면 기차 기차는 빨라',
'빠르면 비행기 비행기는 높아', 
'높으면 백두산',
'더 높은 건 달',
'더 높은 건 별',
'달보다 별보다 더 높은 건', 
'부모님의 사랑']


In [79]:
# sentences=["울퉁불퉁 멋진 몸매에",
# "빠알간 옷을 입고",
# "새콤달콤 향내 풍기는",
# "멋쟁이 토마토 토마토",
# "나는야 주스 될 거야",
# "나는야 케첩 될 거야",
# "나는야 춤을 출 거야",
# "뽐내는 토마토 토마토",
# "울퉁불퉁 멋진 몸매에",
# "빠알간 옷을 입고",
# "새콤달콤 향내 풍기는",
# "멋쟁이 토마토 토마토",
# "나는야 주스 될 거야",
# "나는야 케첩 될 거야",
# "나는야 춤을 출 거야",
# "뽐내는 토마토 토마토"]

# DATASET 만들기

In [5]:
# import torch
# from torch.utils.data import Dataset
# class tomato_dataset(Dataset):
#     def __init__(self,sentences):
#         super().__init__()
# #         내가 tomato dataset = sentences
#         self.tomato=sentences
#         self.features, self.targets = self.vocab()
#         self.features = self.padding()
#         self.features = torch.Tensor(self.features)
#     def vocab(self):
# #         print("vocab이야")
#         features=[]
#         vocab_list=[]
#         targets=[]
#         lst = []
#         for sen in self.tomato:
#             vocab_list.extend(sen.split())
#         vocab_list=set(vocab_list)
#         num_dict={i:idx for i,idx in enumerate(vocab_list,start=1)}
#         word_dict={idx:i for i,idx in enumerate(vocab_list,start=1)}
#         for sen in self.tomato:
#             sen = sen.split()
#             feature = [word_dict[i] for i in sen[:-1]]
#             features.append(feature)
#             target = word_dict[sen[-1]]
#             targets.append(target)
# #             num_list = [word_dict[i] for i in sen]
# #             lst.append(num_list)
#         return features, torch.Tensor(targets)
#     def padding(self):
#         max_len = max(len(l) for l in self.features)
#         for i in self.features:
#             i.extend((max_len-len(i))*[0])
#         return self.features
#     def __len__(self):
#         return len(self.features)
#     def __getitem__(self,idx):
#         return self.features[idx], self.targets[idx]

In [2]:
from torch.utils.data import Dataset
import numpy as np
import torch
from tqdm import tqdm
class M_dataset(Dataset):
    def __init__(self,sentences):
        self.rawdata = sentences # rawdata를 받음
        self.d_list=self.make_list()
        self.feature,self.target,self.vocab_size,self.num_dict,self.word_dict = self.vocab()
        self.feature=self.padding()
        self.feature=torch.LongTensor(self.feature)
        self.target=torch.LongTensor(self.target)
#         self.target= self.target.unsqueeze(dim=1)
    def make_list(self):# list로 만들어줌
        d_list=[]
        for i in self.rawdata:
            d_list.append(i.split())
        return d_list # 리스트로 나오게 함
    def vocab(self): # 단어장 만들기  기능 1. 조회 2 숫자로 변경 ,3문자로 변경
        features=[]
        targets=[]
        vocab_list=[]
        for i in self.rawdata:
            vocab_list.extend(i.split())
        vocab_list=set(vocab_list)
        num_dict={i:idx for i,idx in enumerate(vocab_list,start=1)} # 숫자를 넣으면 문자로 나옴 
        word_dict={idx:i for i,idx in enumerate(vocab_list,start=1)} #  문자를 넣으면 숫자로나옴
        for sen in self.d_list:
            feature = [word_dict[i] for i in sen[:-1]]
            features.append(feature)
            target = word_dict[sen[-1]]
            targets.append(target)
        return features,targets,vocab_list,num_dict,word_dict
    def padding(self):
        padding_lst=[]
        max_len=(max(len(i) for i in self.feature))
        for row in self.feature:
            padding_lst.append([0]*(max_len - len(row))+ row)
        return padding_lst
        
        
    def __len__(self):
        return len(self.feature)
    
    def __getitem__(self,idx):
        return self.feature[idx],self.target[idx]
        


In [3]:
dataset=M_dataset(sentences)

In [48]:
len(dataset.num_dict)+

30

In [22]:
# 데이터 갯수 =문장 갯수
len(dataset)

10

In [49]:
dataset.feature[0]

tensor([0, 0, 7, 8])

In [7]:
# 데이터 타입
type(dataset.feature[0])

torch.Tensor

In [50]:
# 데이터 shape 맟 데이터 값 확인
print(dataset[0][0]) # feature
print(dataset[0][0].shape)
print(dataset[0][1])
print(dataset[0][1].shape) # target unsqueez로 shape 를 맞춰줌 

tensor([0, 0, 7, 8])
torch.Size([4])
tensor(22)
torch.Size([])


# datasetloader 생성

In [51]:
from torch.utils.data import DataLoader
song_dataloader=DataLoader(dataset=dataset,batch_size=1,drop_last=True,shuffle=False)

In [52]:
print(next(iter(song_dataloader)))


[tensor([[0, 0, 7, 8]]), tensor([22])]


In [53]:
dataset.num_dict

{1: '기차',
 2: '바나나',
 3: '높아',
 4: '맛있으면',
 5: '달',
 6: '건',
 7: '원숭이',
 8: '엉덩이는',
 9: '바나나는',
 10: '더',
 11: '길으면',
 12: '비행기는',
 13: '백두산',
 14: '빨라',
 15: '사과는',
 16: '사과',
 17: '사랑',
 18: '별',
 19: '높은',
 20: '달보다',
 21: '별보다',
 22: '빨개',
 23: '기차는',
 24: '맛있어',
 25: '빨가면',
 26: '비행기',
 27: '빠르면',
 28: '길어',
 29: '높으면',
 30: '부모님의'}

In [54]:
# 
print(next(iter(song_dataloader))[0].shape) # batch, feature
print(next(iter(song_dataloader))[0])# feature data
print(next(iter(song_dataloader))[1].shape) # batch, target
print(next(iter(song_dataloader))[1]) # target data 

torch.Size([1, 4])
tensor([[0, 0, 7, 8]])
torch.Size([1])
tensor([22])


# CNN 모델 생성 

In [29]:
# 데이터의 사전 사이즈


In [55]:
# 모델 생성
import torch.nn as nn
class CNN_model(nn.Module):
    def __init__(self,vocab_size,embed_size=64):
        super().__init__()
        self.embediing= torch.nn.Embedding(vocab_size,embed_size) # 임베딩할 사이즈
        self.seq= torch.nn.Sequential(
        torch.nn.Conv1d(in_channels=embed_size,out_channels=embed_size*2,kernel_size=2),
        torch.nn.ReLU(),
        torch.nn.MaxPool1d(kernel_size=1),
        torch.nn.Conv1d(in_channels=embed_size*2,out_channels=embed_size*4,kernel_size=2),
        torch.nn.ReLU(),
        torch.nn.MaxPool1d(kernel_size=1),
        torch.nn.AdaptiveAvgPool1d(1),
        torch.nn.Flatten(),
        torch.nn.Linear(in_features=embed_size*4,out_features=vocab_size)
         )
    def forward(self,x):
        emb_layout=self.embediing(x)
        emb_per_layout=emb_layout.permute(0,2,1)
        predict=self.seq(emb_per_layout)
        return predict
        

In [108]:
# import torch
# import torch.nn as nn

# class CNN_model2(nn.Module):
#     def __init__(self, vocab_size, embed_size=64):
#         super().__init__()
#         self.embedding = torch.nn.Embedding(vocab_size, embed_size)  # 임베딩할 사이즈
#         self.con = torch.nn.Conv1d(in_channels=embed_size, out_channels=embed_size * 2, kernel_size=2)
#         self.relu = torch.nn.ReLU()
#         self.maxpool = torch.nn.MaxPool1d(kernel_size=1)
#         self.adapt = torch.nn.AdaptiveAvgPool1d(1)
#         self.flatten = torch.nn.Flatten()
#         self.linear = torch.nn.Linear(embed_size * 2, vocab_size)
        
#     def forward(self, x):
#         emb_layout = self.embedding(x)
#         emb_per_layout = emb_layout.permute(0, 2, 1)
#         con_layout = self.con(emb_per_layout)
#         relu_layout = self.relu(con_layout)
#         mxp_layout = self.maxpool(relu_layout)
#         adp_layout = self.adapt(mxp_layout)
#         flt_layout = self.flatten(adp_layout)
#         ln_layout = self.linear(flt_layout)
#         return ln_layout

In [110]:
len(dataset.vocab_size)

30

In [56]:
cnn_tomato=CNN_model(len(dataset.vocab_size)+1)

In [57]:
cnn_tomato

CNN_model(
  (embediing): Embedding(31, 64)
  (seq): Sequential(
    (0): Conv1d(64, 128, kernel_size=(2,), stride=(1,))
    (1): ReLU()
    (2): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (3): Conv1d(128, 256, kernel_size=(2,), stride=(1,))
    (4): ReLU()
    (5): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (6): AdaptiveAvgPool1d(output_size=1)
    (7): Flatten(start_dim=1, end_dim=-1)
    (8): Linear(in_features=256, out_features=31, bias=True)
  )
)

torch.Size([1, 4])
tensor([ 0,  0, 28,  6])
torch.Size([1, 4])
tensor([ 0, 12, 26, 19])
torch.Size([1, 4])
tensor([ 0, 25, 29,  5])
torch.Size([1, 4])
tensor([ 0, 27, 30, 24])
torch.Size([1, 4])
tensor([ 0,  8, 13, 15])
torch.Size([1, 4])
tensor([ 0,  0,  0, 14])
torch.Size([1, 4])
tensor([ 0, 16, 18,  3])
torch.Size([1, 4])
tensor([ 0, 16, 18,  3])
torch.Size([1, 4])
tensor([17,  1, 16, 18])
torch.Size([1, 4])
tensor([ 0,  0,  0, 20])


In [120]:
for i in song_dataloader:
    print(i[0].shape)
    print(i[0])

torch.Size([1, 4])
tensor([[ 0,  0, 28,  6]])
torch.Size([1, 4])
tensor([[ 0, 12, 26, 19]])
torch.Size([1, 4])
tensor([[ 0, 25, 29,  5]])
torch.Size([1, 4])
tensor([[ 0, 27, 30, 24]])
torch.Size([1, 4])
tensor([[ 0,  8, 13, 15]])
torch.Size([1, 4])
tensor([[ 0,  0,  0, 14]])
torch.Size([1, 4])
tensor([[ 0, 16, 18,  3]])
torch.Size([1, 4])
tensor([[ 0, 16, 18,  3]])
torch.Size([1, 4])
tensor([[17,  1, 16, 18]])
torch.Size([1, 4])
tensor([[ 0,  0,  0, 20]])


In [37]:
cnn=CNN_model(31)

In [38]:
cnn_test=CNN_model(31)

In [83]:
# 모델 모형 확인

CNN_model(
  (embediing): Embedding(31, 64)
  (seq): Sequential(
    (0): Conv1d(64, 128, kernel_size=(2,), stride=(1,))
    (1): ReLU()
    (2): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (3): Conv1d(128, 256, kernel_size=(2,), stride=(1,))
    (4): ReLU()
    (5): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (6): AdaptiveAvgPool1d(output_size=1)
    (7): Flatten(start_dim=1, end_dim=-1)
    (8): Linear(in_features=256, out_features=31, bias=True)
  )
)

In [39]:
cnn_test

CNN_model(
  (embediing): Embedding(31, 64)
  (seq): Sequential(
    (0): Conv1d(64, 128, kernel_size=(2,), stride=(1,))
    (1): ReLU()
    (2): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (3): Conv1d(128, 256, kernel_size=(2,), stride=(1,))
    (4): ReLU()
    (5): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (6): AdaptiveAvgPool1d(output_size=1)
    (7): Flatten(start_dim=1, end_dim=-1)
    (8): Linear(in_features=256, out_features=31, bias=True)
  )
)

In [112]:
cnn_tomato

CNN_model2(
  (embedding): Embedding(30, 64)
  (con): Conv1d(64, 128, kernel_size=(2,), stride=(1,))
  (relu): ReLU()
  (maxpool): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
  (adapt): AdaptiveAvgPool1d(output_size=1)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear): Linear(in_features=128, out_features=30, bias=True)
)

# 학습 함수 생성연습!

In [58]:
import torch.nn as nn
import torch.optim as optim
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn_tomato.parameters(), lr=0.001)

In [59]:
for batch in song_dataloader:
    print(batch[0]) # batch,feature
    print(batch[1])

tensor([[0, 0, 7, 8]])
tensor([22])
tensor([[ 0, 25, 16, 15]])
tensor([24])
tensor([[0, 4, 2, 9]])
tensor([28])
tensor([[ 0, 11,  1, 23]])
tensor([14])
tensor([[ 0, 27, 26, 12]])
tensor([3])
tensor([[ 0,  0,  0, 29]])
tensor([13])
tensor([[ 0, 10, 19,  6]])
tensor([5])
tensor([[ 0, 10, 19,  6]])
tensor([18])
tensor([[20, 21, 10, 19]])
tensor([6])
tensor([[ 0,  0,  0, 30]])
tensor([17])


In [60]:
# 예측값 생성
for batch in song_dataloader:
    pred = cnn_tomato(batch[0])
    print(pred)

tensor([[-0.0579, -0.0105,  0.1494,  0.1559,  0.0196, -0.0507, -0.0078,  0.1317,
          0.0235,  0.0528, -0.1550,  0.1250, -0.0038,  0.0360, -0.0297, -0.0188,
         -0.0981, -0.1216,  0.2079,  0.1450,  0.0376, -0.0171, -0.0475, -0.2102,
         -0.0959,  0.0643, -0.0832, -0.0305,  0.0309,  0.0529, -0.0873]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.0550, -0.0285,  0.1629,  0.0671, -0.0176, -0.0135,  0.0097,  0.0506,
         -0.0950, -0.0898, -0.0617,  0.0254, -0.0150,  0.1140,  0.0693, -0.1271,
         -0.0286, -0.0828, -0.0151,  0.1872, -0.0222,  0.2305, -0.0958, -0.0958,
         -0.1346,  0.0927, -0.1098, -0.0445,  0.1419,  0.0872, -0.1431]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.0617,  0.0350,  0.0965,  0.0913,  0.0068, -0.0205,  0.0051,  0.0489,
          0.0360, -0.0121, -0.0690,  0.0382,  0.0134,  0.0168, -0.0046, -0.1467,
         -0.0602, -0.0928,  0.0326,  0.1731, -0.0411,  0.0713, -0.1201, -0.1711,
         -0.1608,  0.0981, -0.1146, -0.0739,  0.0018,  0.

# 학습 코드

# CNN_test 모델

In [87]:
# 학습 안됐을때 첫번째 가중치 값
for batch in song_dataloader:
    pred=cnn_test(batch[0])
    print(pred)
# tensor([[-0.1006,  0.2013,  0.0840, -0.0325, -0.0057, -0.0947, -0.2215, -0.0292,
#          -0.1764, -0.1405,  0.0259,  0.0024,  0.1675,  0.1995,  0.1056,  0.0358,
#          -0.0489,  0.0182, -0.0653,  0.0774, -0.0193, -0.0842,  0.0782, -0.2135,
#          -0.0858, -0.0419, -0.0068, -0.1099,  0.2063,  0.2383]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.0162,  0.1080,  0.0934, -0.0705,  0.0156, -0.0783, -0.1610, -0.0623,
#          -0.1395, -0.1657, -0.0897, -0.0840,  0.2818,  0.1920,  0.0999,  0.0571,
#           0.0186,  0.0925,  0.0575,  0.1495, -0.0355, -0.0125,  0.1099, -0.0525,
#          -0.0314, -0.0151, -0.0636, -0.0309,  0.1571,  0.2258]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.1054,  0.1119,  0.0276, -0.1349,  0.0264, -0.0343, -0.1587,  0.0468,
#          -0.0795, -0.1959,  0.0434, -0.1265,  0.1626,  0.1462,  0.1562,  0.0207,
#          -0.0510,  0.0132,  0.0072,  0.1254, -0.0243, -0.0560,  0.0494, -0.2558,
#          -0.0777,  0.0215,  0.0452, -0.1682,  0.2300,  0.1484]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.0877,  0.1738,  0.1382, -0.0935,  0.0149, -0.0675, -0.2082,  0.0362,
#          -0.1536, -0.1560, -0.0277,  0.1045,  0.0932,  0.1171,  0.0771,  0.0212,
#           0.0094, -0.0504, -0.0671,  0.1572, -0.0743, -0.0304,  0.0242, -0.1903,
#          -0.0943,  0.0201,  0.0561, -0.1253,  0.2441,  0.1974]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.1537,  0.0831,  0.1728, -0.1309,  0.1317, -0.0192, -0.1152,  0.0735,
#          -0.1399, -0.2410, -0.0873, -0.0464,  0.1653,  0.1510,  0.1389,  0.1191,
#           0.0731, -0.0129, -0.0532,  0.1519,  0.0109, -0.0876,  0.0070, -0.2428,
#          -0.0755,  0.1125,  0.0120, -0.2078,  0.2550,  0.1923]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.0940,  0.2204,  0.0004, -0.0840, -0.0749, -0.1476, -0.1475,  0.1026,
#          -0.1360, -0.1995,  0.0102, -0.0585,  0.1790,  0.2276,  0.2529, -0.0118,
#          -0.0606, -0.0329, -0.0124,  0.0761, -0.0223, -0.1117,  0.0952, -0.1747,
#          -0.1136, -0.0915,  0.1388, -0.1651,  0.2767,  0.1861]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.0749,  0.1332,  0.1033, -0.1811,  0.1140, -0.0176, -0.1315,  0.0848,
#          -0.1982, -0.2357,  0.0210, -0.0237,  0.1576,  0.2189,  0.1145,  0.0340,
#           0.0145,  0.0746, -0.0870,  0.1150,  0.0384, -0.0558,  0.0223, -0.1974,
#          -0.0289,  0.0123, -0.0637, -0.0863,  0.1398,  0.1191]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.0749,  0.1332,  0.1033, -0.1811,  0.1140, -0.0176, -0.1315,  0.0848,
#          -0.1982, -0.2357,  0.0210, -0.0237,  0.1576,  0.2189,  0.1145,  0.0340,
#           0.0145,  0.0746, -0.0870,  0.1150,  0.0384, -0.0558,  0.0223, -0.1974,
#          -0.0289,  0.0123, -0.0637, -0.0863,  0.1398,  0.1191]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.1376,  0.1419, -0.0074, -0.1412,  0.1193, -0.0338, -0.1675,  0.0452,
#          -0.1503, -0.1819, -0.0164, -0.0429,  0.1626,  0.2050,  0.0722,  0.1273,
#           0.0549,  0.1271, -0.0181,  0.0805, -0.0563, -0.0942,  0.0669, -0.1195,
#          -0.0875, -0.0589, -0.0418, -0.0906,  0.0583,  0.1544]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-0.1031,  0.2248,  0.0159, -0.0690, -0.0385, -0.0974, -0.1700,  0.0919,
#          -0.1887, -0.1862,  0.0818, -0.0572,  0.1531,  0.2132,  0.2202,  0.0023,
#          -0.0516,  0.0270,  0.0032,  0.0020, -0.0705, -0.1498,  0.0885, -0.2283,
#          -0.1225, -0.0916,  0.1155, -0.2187,  0.2301,  0.1568]],
#        grad_fn=<AddmmBackward0>)

tensor([[ 2.7653e-02, -8.9911e-02,  9.8459e-02,  9.5206e-02,  1.3939e-02,
          7.9086e-02, -4.0915e-02,  1.1861e-01,  5.5216e-02, -9.4182e-02,
          1.0842e-01,  2.2270e-02,  1.0716e-02, -1.6130e-01, -1.2937e-01,
         -1.1837e-04, -3.3651e-02, -4.5009e-02,  3.6891e-02, -1.4616e-01,
          9.5682e-02,  6.0766e-02,  6.0504e-02, -3.7315e-03,  5.4990e-02,
          1.2812e-01,  1.2851e-01, -9.9503e-02, -8.7652e-02, -2.0280e-02,
          1.5248e-01]], grad_fn=<AddmmBackward0>)
tensor([[-0.0336, -0.0682,  0.0912,  0.0896,  0.0196,  0.1011, -0.0373,  0.0814,
          0.0634, -0.0105,  0.1415,  0.0724, -0.1030, -0.1128, -0.1410, -0.0771,
         -0.0308,  0.0011,  0.0024, -0.2456,  0.0882,  0.0325,  0.0105, -0.0594,
          0.0740,  0.1200,  0.1650, -0.0760, -0.0628,  0.0224,  0.2337]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.0699, -0.0789,  0.1256,  0.0565,  0.0127,  0.1339,  0.0661, -0.0065,
          0.0505, -0.0499,  0.1204,  0.0716, -0.0065, -0.1302, -0.1179,  0.

In [70]:
# 학습을 위한 cnn_test 손실함수,옵티마이저 생성
import torch.nn as nn
import torch.optim as optim
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn_test.parameters(), lr=0.001)

In [198]:
N_EPOCH=1
pred_num=0
for epoch in range(N_EPOCH):

    cnn_test.train()
    epoch_loss = 0
    for batch in song_dataloader:
        pred = cnn_test(batch[0]) # feature 를 모델에 넣음
        print("#"*20)
        print('정답'+pred)
        print("실제 값"+batch[1])
        if pred.argmax(dim=-1)==batch[1]:
            pred_num+=1
        loss = loss_fn(pred,torch.tensor(batch[1], dtype=torch.long))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        epoch_loss+=loss.item()
        print()
#     iepoch%10==0:
#     print(f"{epoch}")
#     print(f"{epoch_loss:.6f}")

C:\Users\Playdata\AppData\Local\Temp\ipykernel_10916\184712336.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  loss = loss_fn(pred,torch.tensor(batch[1], dtype=torch.long))


0
34.901820
1
27.354216
2
20.213984
3
13.039364
4
7.808337
5
4.908771
6
3.404972
7
2.687332
8
2.275398
9
2.034171
10
1.888735
11
1.798252
12
1.737492
13
1.695799
14
1.665601
15
1.642969
16
1.625811
17
1.611308
18
1.599911
19
1.589641
20
1.581545
21
1.574062
22
1.567471
23
1.561040
24
1.556111
25
1.551044
26
1.546809
27
1.542992
28
1.539189
29
1.536236
30
1.532497
31
1.529639
32
1.527150
33
1.524597
34
1.521944
35
1.519502
36
1.517290
37
1.515331
38
1.513213
39
1.511371


In [217]:
for batch in song_dataloader:
    pred=cnn_test(batch[0])
    print(pred)
##########################
# 40epoch 돌렸을 때 나온 결과
# tensor([[ -2.7031, -11.9725,  -2.4879, -11.9993, -11.9782,  -2.8094, -13.3631,
#          -13.2695, -12.6752, -11.4285,  -5.0202, -12.0012, -10.2563, -11.4767,
#          -10.7292, -12.1461,   5.8633,  -2.8378, -12.1131, -11.3112,  -2.1962,
#          -13.0080, -12.6742, -11.7996,  -1.3102, -11.5281, -12.2547,  -2.3779,
#          -11.0740,  -2.3969]], grad_fn=<AddmmBackward0>)
# tensor([[  7.0027,  -8.7669,  -1.7697,  -9.3753,  -8.3081,  -3.3236, -10.1632,
#           -9.1857,  -9.3100,  -9.5374,  -1.9028,  -8.5034,  -8.0532,  -8.0124,
#           -9.3462,  -9.4987,  -1.4498,  -1.4598,  -8.6125,  -7.9787,  -4.6505,
#           -9.3860,  -8.9365,  -8.8678,  -1.6382,  -9.5421,  -9.7537,  -2.2215,
#           -8.0269,  -1.9990]], grad_fn=<AddmmBackward0>)
# tensor([[ -4.0472,  -9.3145,  -2.3747,  -8.9656,  -8.6706,   6.8229,  -9.7370,
#           -9.2182, -10.0845, -10.0287,  -2.3350,  -9.8866,  -8.9287,  -9.0470,
#           -9.2082,  -9.1185,  -1.6935,  -2.5873,  -8.5311,  -8.7647,  -2.3406,
#          -10.5814,  -9.4350, -10.0092,  -3.8742,  -9.0763,  -9.2215,  -2.9817,
#           -9.1799,  -1.9082]], grad_fn=<AddmmBackward0>)
# tensor([[ -1.8404,  -9.2478,  -2.6055,  -9.3799,  -8.9404,  -2.5274, -10.0963,
#           -9.0646, -10.6040, -10.2449,  -3.3469,  -9.6702,  -8.3254,  -9.2443,
#           -9.5489,  -9.2820,  -1.9441,   6.7993,  -9.7973,  -9.0710,  -3.2699,
#          -10.4312,  -9.8429,  -9.0070,  -2.0537,  -8.6197,  -9.1455,  -2.7977,
#           -9.1236,  -1.2247]], grad_fn=<AddmmBackward0>)
# tensor([[ -2.4238, -10.3733,  -2.0900,  -9.7678,  -9.6864,  -1.8439, -10.8490,
#          -10.5772, -10.9149, -10.8132,  -3.5857,  -9.8900,  -9.2856,  -9.9737,
#           -9.9254, -10.6961,  -0.5705,  -0.8899, -10.8480,  -9.2301,  -4.9092,
#          -11.2831, -10.4872, -10.7752,  -6.0453,  -9.6741, -10.4603,  -2.1022,
#           -9.4890,   7.4161]], grad_fn=<AddmmBackward0>)
# tensor([[ -1.8670, -12.1733,  -5.3224, -12.1679, -12.4552,  -4.3945, -13.2095,
#          -12.3533, -13.4372, -12.8989,  -3.7856, -13.2153, -11.0651, -11.3992,
#          -11.3764, -12.8729,  -0.1697,  -2.5661, -12.0369, -11.5464,   0.9094,
#          -13.1796, -12.8122, -11.8615,   7.0341, -11.4977, -11.6803,  -6.0019,
#          -10.7262,  -6.4504]], grad_fn=<AddmmBackward0>)
# tensor([[-2.3287, -6.6100,  4.6647, -8.2770, -6.8958, -2.3216, -7.3407, -6.7913,
#          -7.2196, -7.6441, -1.7404, -6.7195, -6.5516, -6.2942, -6.5720, -7.5338,
#          -1.6324, -2.7080, -6.5021, -6.5138, -2.5506, -7.3329, -7.2351, -7.5969,
#          -4.3938, -6.9907, -7.3539,  4.6763, -6.0248, -2.6286]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-2.3287, -6.6100,  4.6647, -8.2770, -6.8958, -2.3216, -7.3407, -6.7913,
#          -7.2196, -7.6441, -1.7404, -6.7195, -6.5516, -6.2942, -6.5720, -7.5338,
#          -1.6324, -2.7080, -6.5021, -6.5138, -2.5506, -7.3329, -7.2351, -7.5969,
#          -4.3938, -6.9907, -7.3539,  4.6763, -6.0248, -2.6286]],
#        grad_fn=<AddmmBackward0>)
# tensor([[-2.1731, -7.0494, -1.0025, -7.6107, -6.8558, -2.0992, -8.2629, -6.9078,
#          -7.9558, -7.5021,  6.7887, -7.0858, -7.9156, -7.0585, -6.8434, -7.4418,
#          -3.1637, -3.3134, -7.6247, -7.3392, -4.0432, -8.7068, -7.5393, -7.7065,
#          -3.4753, -7.7944, -8.0575, -1.3812, -5.8739, -2.8182]],
#        grad_fn=<AddmmBackward0>)
# tensor([[ -4.3755, -10.9972,  -2.8328, -11.3686, -11.5907,  -2.2695, -12.1595,
#          -11.7262, -12.7580, -12.0458,  -4.3373, -12.5409, -10.9212, -11.2670,
#          -11.0812, -12.5933,  -0.8282,  -2.3781, -11.2155, -11.3725,   7.1565,
#          -12.4915, -12.3089, -11.5461,   1.2338, -10.3994, -11.0288,  -3.6560,
#          -10.7484,  -4.6884]], grad_fn=<AddmmBackward0>)

tensor([[ -2.7031, -11.9725,  -2.4879, -11.9993, -11.9782,  -2.8094, -13.3631,
         -13.2695, -12.6752, -11.4285,  -5.0202, -12.0012, -10.2563, -11.4767,
         -10.7292, -12.1461,   5.8633,  -2.8378, -12.1131, -11.3112,  -2.1962,
         -13.0080, -12.6742, -11.7996,  -1.3102, -11.5281, -12.2547,  -2.3779,
         -11.0740,  -2.3969]], grad_fn=<AddmmBackward0>)
tensor([[  7.0027,  -8.7669,  -1.7697,  -9.3753,  -8.3081,  -3.3236, -10.1632,
          -9.1857,  -9.3100,  -9.5374,  -1.9028,  -8.5034,  -8.0532,  -8.0124,
          -9.3462,  -9.4987,  -1.4498,  -1.4598,  -8.6125,  -7.9787,  -4.6505,
          -9.3860,  -8.9365,  -8.8678,  -1.6382,  -9.5421,  -9.7537,  -2.2215,
          -8.0269,  -1.9990]], grad_fn=<AddmmBackward0>)
tensor([[ -4.0472,  -9.3145,  -2.3747,  -8.9656,  -8.6706,   6.8229,  -9.7370,
          -9.2182, -10.0845, -10.0287,  -2.3350,  -9.8866,  -8.9287,  -9.0470,
          -9.2082,  -9.1185,  -1.6935,  -2.5873,  -8.5311,  -8.7647,  -2.3406,
         -10.5814

In [26]:
# 예측 값이 정말로 전부 합쳤을 때 확률 1로 나오는지 확인
def convert_exponential_to_decimal(numbers):
    decimal_numbers = []

    for num in numbers:
        decimal_numbers.append('{:.10f}'.format(num))

    return decimal_numbers

# 주어진 숫자 리스트 (지수 표기법)
exponential_numbers = [1.8995e-04, 1.7906e-08, 2.3556e-04, 1.7432e-08, 1.7804e-08, 1.7079e-04,
                       4.4573e-09, 4.8947e-09, 8.8675e-09, 3.0849e-08, 1.8721e-05, 1.7399e-08,
                       9.9611e-08, 2.9397e-08, 6.2081e-08, 1.5051e-08, 9.9762e-01, 1.6601e-04,
                       1.5558e-08, 3.4689e-08, 3.1535e-04, 6.3573e-09, 8.8762e-09, 2.1284e-08,
                       7.6483e-04, 2.7924e-08, 1.3503e-08, 2.6295e-04, 4.3974e-08, 2.5800e-04]

# 지수 표기법을 일반적인 소수 표기법으로 변환
decimal_numbers = convert_exponential_to_decimal(exponential_numbers)

# 변환된 숫자들 출력
result=0
for num in decimal_numbers:
    result+=float(num) # 확률들 다 더하는거
#     print(num)
print(result) # 결과
        

1.0000026591


In [50]:
a=[1.8995e-04, 1.7906e-08, 2.3556e-04, 1.7432e-08, 1.7804e-08, 1.7079e-04,
         4.4573e-09, 4.8947e-09, 8.8675e-09, 3.0849e-08, 1.8721e-05, 1.7399e-08,
         9.9611e-08, 2.9397e-08, 6.2081e-08, 1.5051e-08, 9.9762e-01, 1.6601e-04,
         1.5558e-08, 3.4689e-08, 3.1535e-04, 6.3573e-09, 8.8762e-09, 2.1284e-08,
         7.6483e-04, 2.7924e-08, 1.3503e-08, 2.6295e-04, 4.3974e-08, 2.5800e-04]
sum(a)

1.0000026589150002

In [51]:
import torch.nn.functional as F
for batch in song_dataloader:
    pred=cnn_test(batch[0])
    # pred는 확률값으로 나온게 아니라 그냥 30개의 가중치로 나옴 
    # 가중치 의 합은 1이 아니다 왜냐하면 실제 정답값과 비슷할수록 그 해당되는 값이 커지고 해당되지 않은 값은 작아지게 만든다
    softmax_pred = F.softmax(pred, dim=1) 
    # 그 30개의 가중치의 출력값이 softmax를 하면 0~1사이로 만들어줘서 30개 중에서 값이 큰값은 큰 확률을 가지고
    # 그렇지 않은 값은 작은 값을 가진다
#     print(softmax_pred)
    
    soft=softmax_pred.detach().numpy()
    print(len(soft[0][0]))

NameError: name 'cnn_test' is not defined

In [ ]:
정확도 표시하는법 아직 모르고 
loss 그래프 표시하는거 아직 모르고
    epoch_loss /= len(dataloader) # 에폭별 loss 계산 - 배치들 평균
    total_acc /= len(dataloader)  #  에폭별 acc 계산 - 배치들 평균
    

# CNN 모델

In [88]:
# 학습을 위한 손실함수,옵티마이저 생성
import torch.nn as nn
import torch.optim as optim
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn.parameters(), lr=0.001)

In [89]:
N_EPOCH=40
for epoch in range(N_EPOCH):

    cnn.train()
    epoch_loss = 0
    for batch in song_dataloader:
        pred = cnn(batch[0]) # feature 를 모델에 넣음
#         print(pred.shape)
#         print(torch.tensor(batch[1], dtype=torch.long).shape)
        loss = loss_fn(pred,torch.tensor(batch[1], dtype=torch.long))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        epoch_loss+=loss.item()
#     if epoch%100==0:
    print(f"{epoch}")
    print(f"{epoch_loss:.6f}")
    
# 39
# Loss:1.511371

C:\Users\Playdata\AppData\Local\Temp\ipykernel_21892\3959523747.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  loss = loss_fn(pred,torch.tensor(batch[1], dtype=torch.long))


0
35.380383
1
29.008343
2
21.748074
3
13.300318
4
7.384314
5
4.794403
6
3.598320
7
2.923731
8
2.514438
9
2.235193
10
2.046475
11
1.913622
12
1.824149
13
1.763723
14
1.719417
15
1.687241
16
1.663323
17
1.648453
18
1.630702
19
1.617524
20
1.606404
21
1.596933
22
1.588660
23
1.582585
24
1.574249
25
1.568043
26
1.561939
27
1.556441
28
1.551731
29
1.547990
30
1.543849
31
1.539918
32
1.536497
33
1.534695
34
1.530304
35
1.528035
36
1.523918
37
1.520507
38
1.518778
39
1.516025


In [199]:
for batch in song_dataloader:
    pred=cnn_test(batch[0])
    print(pred)

tensor([[ -2.7031, -11.9725,  -2.4879, -11.9993, -11.9782,  -2.8094, -13.3631,
         -13.2695, -12.6752, -11.4285,  -5.0202, -12.0012, -10.2563, -11.4767,
         -10.7292, -12.1461,   5.8633,  -2.8378, -12.1131, -11.3112,  -2.1962,
         -13.0080, -12.6742, -11.7996,  -1.3102, -11.5281, -12.2547,  -2.3779,
         -11.0740,  -2.3969]], grad_fn=<AddmmBackward0>)
tensor([[  7.0027,  -8.7669,  -1.7697,  -9.3753,  -8.3081,  -3.3236, -10.1632,
          -9.1857,  -9.3100,  -9.5374,  -1.9028,  -8.5034,  -8.0532,  -8.0124,
          -9.3462,  -9.4987,  -1.4498,  -1.4598,  -8.6125,  -7.9787,  -4.6505,
          -9.3860,  -8.9365,  -8.8678,  -1.6382,  -9.5421,  -9.7537,  -2.2215,
          -8.0269,  -1.9990]], grad_fn=<AddmmBackward0>)
tensor([[ -4.0472,  -9.3145,  -2.3747,  -8.9656,  -8.6706,   6.8229,  -9.7370,
          -9.2182, -10.0845, -10.0287,  -2.3350,  -9.8866,  -8.9287,  -9.0470,
          -9.2082,  -9.1185,  -1.6935,  -2.5873,  -8.5311,  -8.7647,  -2.3406,
         -10.5814

In [ ]:
# 왜 안되는지 물어보기!!!

In [97]:
len(song_dataloader)

10

In [117]:
a=[30  2]
b=[30  2]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (190792197.py, line 1)

In [ ]:
def acc_per(dataset,data_loader,model,loss_fn):
    model.eval() # 모델을 평가모드로 전환
    acc_=0 # 정확도 값 초기화
    for batch in data_loader: # 데이터로더로 배치단위로 
        eva=model(batch[0]) #  모델에 배치단위인 데이터를 넣어 예측값을 eva에 저장
        pred_output=[dataset.num_dict[i] for i in eva.argmax(dim=-1).numpy()] # 예측값 확인 용도
        print(pred_output)
        batch_output=[dataset.num_dict[i] for i in batch[1].numpy()] # 실제값 확인 용도
        print(batch_output)
        acc_+=accuracy_score(batch[1].numpy(),eva.argmax(dim=-1).numpy()) # 정확도 계산 용도
    
    print("총 맞은 갯수: ",acc_)
    batch_num=len(song_dataloader) # 배치수 확인 용도 
    per=
    print("배치 수: ",len(song_dataloader))
    print("확률:",(acc_/len(song_dataloader))*100)
    print("총 데이터 갯수:",len(eva)*len(song_dataloader)) # 배치 * 데이터 loader의 길이
    return acc_,

In [143]:
from sklearn.metrics import accuracy_score
cnn.eval()
pred_num=0
acc_=0
for batch in song_dataloader:
    eva=cnn(batch[0])
#     print(eva)
    
#     print(eva.argmax(dim=-1))
    pred_output=[dataset.num_dict[i] for i in eva.argmax(dim=-1).numpy()]
    print(pred_output)
    batch_output=[dataset.num_dict[i] for i in batch[1].numpy()]
    print(batch_output)
#     print(batch[1])
#     print(batch[1].numpy())
#     print(len(eva))
    acc_+=accuracy_score(batch[1].numpy(),eva.argmax(dim=-1).numpy())
    print(acc_)
print("총 맞은 갯수: ",acc_)
print("배치 수: ",len(song_dataloader))
print("확률:",(acc_/len(song_dataloader))*100)
print("총 데이터 갯수:",len(eva)*len(song_dataloader)) # 배치 * 데이터 loader의 길이

['빨개', '맛있어']
['빨개', '맛있어']
1.0
['길어', '빨라']
['길어', '빨라']
2.0
['높아', '백두산']
['높아', '백두산']
3.0
['달', '달']
['달', '별']
3.5
['건', '사랑']
['건', '사랑']
4.5
총 맞은 갯수:  4.5
배치 수:  5
확률: 90.0
총 데이터 갯수: 10


In [134]:
sentences= ['원숭이 엉덩이는 빨개',
'빨가면 사과 사과는 맛있어', 
'맛있으면 바나나 바나나는 길어', 
'길으면 기차 기차는 빨라',
'빠르면 비행기 비행기는 높아', 
'높으면 백두산',
'더 높은 건 달',
'더 높은 건 별',
'달보다 별보다 더 높은 건', 
'부모님의 사랑']

In [137]:
num_dict[4,6]

KeyError: (4, 6)

In [133]:
dataset.word_dict

{'엉덩이는': 1,
 '맛있어': 2,
 '원숭이': 3,
 '부모님의': 4,
 '빨가면': 5,
 '건': 6,
 '비행기는': 7,
 '맛있으면': 8,
 '바나나': 9,
 '높으면': 10,
 '길으면': 11,
 '사랑': 12,
 '높은': 13,
 '별보다': 14,
 '기차는': 15,
 '빠르면': 16,
 '높아': 17,
 '길어': 18,
 '사과는': 19,
 '사과': 20,
 '기차': 21,
 '달보다': 22,
 '빨라': 23,
 '백두산': 24,
 '더': 25,
 '비행기': 26,
 '별': 27,
 '달': 28,
 '바나나는': 29,
 '빨개': 30}

In [ ]:
eva=cnn(song)

In [ ]:
pred_max = pred.argmax(dim=1)